services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hw02_app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app

  postgres:
    image: postgres:13
    container_name: hw02_postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
